---
title: "Quiz1"
output: html_document
---

Download the file
```{r}
library('data.table')
if(!file.exists("data")) {
    dir.create("data")
}
download.file('https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv', destfile='data/ss06hid.csv', method="curl")
```

Load table
```{r}
dt <- fread('data/ss06hid.csv')
```

Look at VAL (Property Value) variable
```{r}
dt[, table(VAL)]
dt[, .N, by=VAL]

sum(dt[, VAL==24], na.rm = TRUE)
```

Excel
```{r}
library('xlsx')
download.file('https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FDATA.gov_NGAP.xlsx', destfile='data/gov_NGAP.xlsx', method="curl")
data <- read.xlsx("data/gov_NGAP.xlsx", sheetIndex = 1, header = TRUE, startRow = 18, endRow = 23)
dat <- data[, 7:15]
sum(dat$Zip*dat$Ext,na.rm=T) 
```

XML
```{r}
library('XML')
download.file('https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml', destfile='data/restaurants.xml', method="curl")
doc <- xmlTreeParse('./data/restaurants.xml', useInternalNodes = TRUE)
rootNode <- xmlRoot(doc)
length(xpathSApply(rootNode, "//zipcode[text()=21231]", xmlValue))
```

```{r}
library('data.table')
download.file('https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06pid.csv', destfile='data/ss06pid.csv', method="curl")
DT <- fread('data/ss06pid.csv')
system.time(tapply(DT$pwgtp15,DT$SEX,mean))
system.time({mean(DT[DT$SEX==1,]$pwgtp15); mean(DT[DT$SEX==2,]$pwgtp15)})
system.time(sapply(split(DT$pwgtp15,DT$SEX),mean))
#system.time({rowMeans(DT)[DT$SEX==1]; rowMeans(DT)[DT$SEX==2]})
system.time(mean(DT$pwgtp15,by=DT$SEX))
# This one makes use of the data.table package!
system.time(DT[,mean(pwgtp15),by=SEX])
```
