---
title: "Quiz3"
output: html_document
---

```{r reviewDownload, cache=TRUE}
if(!file.exists("./data")){dir.create("./data")}
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv", destfile="./data/ss06hid.csv", method="curl")
data <- read.csv("./data/ss06hid.csv")
```

```{r}
names(data)
agricultureLogical <- data$ACR == 3 & data$AGS == 6
head(agricultureLogical)
r <- data[which(agricultureLogical), ]
head(r)
```


```{r reviewDownload, cache=TRUE}
#install.packages("jpeg")
library("jpeg")
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg ", destfile="./data/jeff.jpg", method="curl")
img <- readJPEG(source="./data/jeff.jpg", native = TRUE)
quantile(img, c(0.30,0.80))
```


```{r reviewDownload, cache=TRUE}
if(!file.exists("./data")){dir.create("./data")}
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv", destfile="./data/domesticProduct.csv", method="curl")
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv ", destfile="./data/education.csv", method="curl")
dp <- read.csv("./data/domesticProduct.csv", header = FALSE, skip=5, nrows=190)
edu <- read.csv("./data/education.csv", header=FALSE, skip=1)
```

```{r}
library(dplyr)
dp <- tbl_df(dp)
edu <- tbl_df(edu)
dp2 <- select(dp, V1, V2, V4, V5)

edu2 <- select(edu, V1, V3)
merged <- merge(dp2, edu2, by.x="V1", by.y="V1", all=FALSE)
m <- tbl_df(merged)
nrow(merged)
r <- arrange(m, desc(V2))
r[13, ]

ig <- group_by(m, V3)
summarize(ig, income=mean(V2))

m$group <- cut(m$V2, breaks=5)
table(m$V3, m$group)
```