---
title: "ReadingData"
output: html_document
---

# Readin data from MYSQL

```R
install.packages("RMySQL")

or on ubuntu: 
sudo aptitude install r-cran-rmysql
```

```{r}
library("RMySQL")

ucscDb <- dbConnect(MySQL(), user="genome", host="genome-mysql.cse.ucsc.edu")
result <- dbGetQuery(ucscDb, "show databases;")
dbDisconnect(ucscDb)

result
```

```{r}
library("RMySQL")

hg19 <- dbConnect(MySQL(), user="genome", db="hg19", host="genome-mysql.cse.ucsc.edu")
allTables <- dbListTables(hg19)
length(allTables)
head(allTables)
dbListFields(hg19, "affyU133Plus2")
dbGetQuery(hg19, "select count(*) from affyU133Plus2")
# read whole table
affyData <- dbReadTable(hg19, "affyU133Plus2")
head(affyData)
# Read subset
query <- dbSendQuery(hg19, "select * from affyU133Plus2 where misMatches between 1 and 3")
affyMis <- fetch(query)
quantile(affyMis$misMatches)

# fetch some rows
affySmall <- fetch(query, n=10)
dbClearResult(query)
dim(affySmall)

dbDisconnect(hg19)
```

# Reading HDF5

http://www.hdfgroup.com

Hierarchical data format.

```R
source('http://bioconductor.org/biocLite.R')
biocLite('rhdf5')

library('rhdf5')

created <- h5createFile('example.h5')
created <- h5createGroup('example.h5', 'foo')
created <- h5createGroup('example.h5', 'bar')
created <- h5createGroup('example.h5', 'foo/foobar')
h5ls("example.h5")

a <- matrix(1:10, nr=5, nc=2) 
h5write(a, 'example.h5', "foo/a")
b <- array(seq(0.1, 2.0, by=0.1), dim=c(5,2,2))
attr(b, 'scale') <- "liter"
h5write(b, 'example.h5', "foo/foobar/b")
h5ls('example.h5')

df <- data.frame(1L:5L, seq(0,1, length.out=5), c('ab', 'cde', 'fghi', 'a', 's'), stringAsFactors=FALSE)
h5write(df, 'example.h5', "df")
h5ls('example.h5')

A <- h5read('example.h5', 'foo/a')
A
```

# Read data from the Web
## XML
see GettingAndCleaningData.

## Reading html

```R
install.packages('httr')
```

```R
library('httr')
con <- url('http://scholar.google.ch/citations?user=HI-I6C0AAAAJ&hl=en')
htmlCode <- readLines(con)
close(con)
htmlCode
```


```{r}
library(XML)
library('httr')
html2 <- GET('http://scholar.google.ch/citations?user=HI-I6C0AAAAJ&hl=en')
content2 <- content(html2, as="text")
parsedHtml <- htmlParse(content2, asText=TRUE)
xpathSApply(parsedHtml, "//title", xmlValue)
```

Authentication
```R
html2 <- GET(url, authenticate('user', 'password))
```

Handles. Cookies and authentication will be stored.

```R
google <- handle('http://google.com')
pg1 <- GET(handle=google, path="/")
pg2 <- GET(handle=google, path="search")
```

# Reading from APIs (JSON)

## OAUTH

```R
library('httr')
library(jsonlite)
myapp <- oauth_app('twitter', key="someKey", secret="someSecret")
sig <- sign_oauth1.0(myapp, token="someToken", token_secret="someTokenSecret")
homeTL <- GET('https://api.twitter.com/1.1/statuses/home_timeline.json', sig)
json1 <- content(homeTL)
json2 <- jsonlite::fromJSON(toJSON(json1))
json2


# Other sources

```R
install.packages('foreign')
read.octava(...)
```

Weka, Stata, Minilab, Octava, SPSS, SAS


## GIS

- rgdal
- rgeos
- raster

## Music

- tuneR
- seewave
